project:
  type: website

website:
  title: "HdM-Projekte"
  description: "Projektangebote von Prof. Dr. Jan Kirenz an der Hochschule der Medien Stuttgart"
  navbar:
    left:
      - href: index.qmd
        text: Start
      - href: projekte/ws-2026/index.qmd
        text: "Wintersemester 2026/27"
      - href: technologien/index.qmd
        text: Technologien
      - href: projekte/archiv/index.qmd
        text: Archiv
  page-footer:
    center: "Prof. Dr. Jan Kirenz · Hochschule der Medien Stuttgart"

format:
  html:
    theme: custom.scss
    toc: true
    lang: de
